### ISSUE TITLE
fix: sharp build error v5.1.5

### ISSUE THREAD

**Issue by dvanmali** [nuxt-modules/og-image#371]
### 🐛 The bug

When upgrading from v5.1.4 to v5.1.5, a sharp build error is generated even though sharp shouldn't be used. Currently the configuration setting is empty and thus uses Satori.

```text
Something went wrong installing the "sharp" module Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
Require stack:
- ./node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/sharp.js
- ./node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/constructor.js
- ./node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/index.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
```

### 🌈 Expected behavior

Sharp module should not be called.

### ℹ️ Additional context

Issue was caused by the changes to [src/module.ts](https://github.com/nuxt-modules/og-image/blob/db2bb7691af186e6ea18e767c8343bdc28742e8b/src/module.ts#L231) in #370

**Comment by harlan-zw** [comment]
Thanks!
