### ISSUE TITLE
fix: error 500 on build since v4.0.2

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/og-image#297]
### 🐛 The bug

Since v4.0.2, the og image pages show a 500 internal server error for built projects (dev mode works fine).

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-mvs7radq?file=pages%2Findex.vue

### 🌈 Expected behavior

There is no sudden 500 error

### ℹ️ Additional context

Logs show:
```
[nuxt] [request error] [unhandled] [500] Cannot find module '/home/jonas/Downloads/nuxt-starter-mvs7radq/.output/server/node_modules/vue/server-renderer/index.mjs' imported from /home/jonas/Downloads/nuxt-starter-mvs7radq/.output/server/chunks/routes/renderer.mjs
```

**Comment by harlan-zw** [comment]
Hmm strange.

Only time I've seen this is when it's a Vue dependency conflict issue, which can be fixed by clearing your lock file and reinstalling or locking the dependency

**Comment by dargmuesli** [comment]
That doesn't seem to help when I try it, I've downgraded to v4.0.1 in my projects for now.

**Comment by dargmuesli** [comment]
Actually, dev mode seems also impacted: when I use a 

```html
<img src="/assets/static/images/picture.jpg" />
```

The server logs `ERROR  Can't load image https://localhost:3000/assets/static/images/picture.jpg?1736676394724: fetch failed`.

Text and colors render fine.

**Comment by harlan-zw** [comment]
Is this in your public directory?

**Comment by dargmuesli** [comment]
Yes, loading that works in v`4.0.1`.

**Comment by dargmuesli** [comment]
Interesting: loading an `<img src="assets/image.svg" />` works but an `<img src="assets/image.jpg" />` (jpg vs. svg) seems not, with images being in the `assets` directory. Haven't found another path to be working with images in the `public` directory yet.

**Comment by harlan-zw** [comment]
I did a quick investigation on this and found some issues relating to how it was resolving the image path when used from the public directory. 

I suspect this will solve the above issue as if it failed to find an image it would fallback to SVG file format.

**Comment by dargmuesli** [comment]
Is fixed for me, thank you! 🚀
